// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using server.Models;

#nullable disable

namespace server.Migrations
{
    [DbContext(typeof(TechsportiaDbContext))]
    [Migration("20260426092137_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("server.Models.College", b =>
                {
                    b.Property<int>("CollegeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CollegeId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<bool?>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CollegeId")
                        .HasName("PK__Colleges__294095397F60ED59");

                    b.HasIndex(new[] { "Email" }, "UQ__Colleges__A9D10534023D5A04")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Colleges");
                });

            modelBuilder.Entity("server.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<int?>("CollegeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("MaxSports")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(150)
                        .IsUnicode(false)
                        .HasColumnType("varchar(150)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("EventId")
                        .HasName("PK__Events__7944C810117F9D94");

                    b.HasIndex("CollegeId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("server.Models.IndividualRegistration", b =>
                {
                    b.Property<int>("IndividualRegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IndividualRegistrationId"));

                    b.Property<bool?>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("RegisteredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("SportId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("IndividualRegistrationId")
                        .HasName("PK__Individu__B7721C9C29572725");

                    b.HasIndex("SportId");

                    b.HasIndex("UserId");

                    b.ToTable("IndividualRegistrations");
                });

            modelBuilder.Entity("server.Models.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<int?>("SportId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ResultId")
                        .HasName("PK__Results__9769020837A5467C");

                    b.HasIndex("SportId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Results");
                });

            modelBuilder.Entity("server.Models.Score", b =>
                {
                    b.Property<int>("ScoreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScoreId"));

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<int?>("SportId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<double?>("Value")
                        .HasColumnType("float");

                    b.HasKey("ScoreId")
                        .HasName("PK__Scores__7DD229D130F848ED");

                    b.HasIndex("SportId");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Scores");
                });

            modelBuilder.Entity("server.Models.Sport", b =>
                {
                    b.Property<int>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SportId"));

                    b.Property<string>("AdditionalDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("MaxPlayers")
                        .HasColumnType("int");

                    b.Property<int?>("MaxSubstitutes")
                        .HasColumnType("int");

                    b.Property<int?>("MinPlayers")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("RegistrationEndDate")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("RegistrationStartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Rules")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SportId")
                        .HasName("PK__Sports__7A41AF3C173876EA");

                    b.HasIndex("EventId");

                    b.ToTable("Sports");
                });

            modelBuilder.Entity("server.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("SportId")
                        .HasColumnType("int");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId")
                        .HasName("PK__Teams__123AE7991CF15040");

                    b.HasIndex("SportId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("server.Models.TeamMember", b =>
                {
                    b.Property<int>("TeamMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamMemberId"));

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TeamMemberId")
                        .HasName("PK__TeamMemb__C7C092E5239E4DCF");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("CollegeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4C07F6335A");

                    b.HasIndex("CollegeId");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D105340AD2A005")
                        .IsUnique()
                        .HasFilter("[Email] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("server.Models.Event", b =>
                {
                    b.HasOne("server.Models.College", "College")
                        .WithMany("Events")
                        .HasForeignKey("CollegeId")
                        .HasConstraintName("FK_Events_College");

                    b.Navigation("College");
                });

            modelBuilder.Entity("server.Models.IndividualRegistration", b =>
                {
                    b.HasOne("server.Models.Sport", "Sport")
                        .WithMany("IndividualRegistrations")
                        .HasForeignKey("SportId")
                        .HasConstraintName("FK_IndReg_Sport");

                    b.HasOne("server.Models.User", "User")
                        .WithMany("IndividualRegistrations")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_IndReg_User");

                    b.Navigation("Sport");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Models.Result", b =>
                {
                    b.HasOne("server.Models.Sport", "Sport")
                        .WithMany("Results")
                        .HasForeignKey("SportId")
                        .HasConstraintName("FK_Results_Sport");

                    b.HasOne("server.Models.Team", "Team")
                        .WithMany("Results")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK_Results_Team");

                    b.HasOne("server.Models.User", "User")
                        .WithMany("Results")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Results_User");

                    b.Navigation("Sport");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Models.Score", b =>
                {
                    b.HasOne("server.Models.Sport", "Sport")
                        .WithMany("Scores")
                        .HasForeignKey("SportId")
                        .HasConstraintName("FK_Scores_Sport");

                    b.HasOne("server.Models.Team", "Team")
                        .WithMany("Scores")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK_Scores_Team");

                    b.HasOne("server.Models.User", "User")
                        .WithMany("Scores")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Scores_User");

                    b.Navigation("Sport");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Models.Sport", b =>
                {
                    b.HasOne("server.Models.Event", "Event")
                        .WithMany("Sports")
                        .HasForeignKey("EventId")
                        .HasConstraintName("FK_Sports_Event");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("server.Models.Team", b =>
                {
                    b.HasOne("server.Models.Sport", "Sport")
                        .WithMany("Teams")
                        .HasForeignKey("SportId")
                        .HasConstraintName("FK_Teams_Sport");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("server.Models.TeamMember", b =>
                {
                    b.HasOne("server.Models.Team", "Team")
                        .WithMany("TeamMembers")
                        .HasForeignKey("TeamId")
                        .HasConstraintName("FK_TeamMembers_Team");

                    b.HasOne("server.Models.User", "User")
                        .WithMany("TeamMembers")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_TeamMembers_User");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.HasOne("server.Models.College", "College")
                        .WithMany("Users")
                        .HasForeignKey("CollegeId")
                        .HasConstraintName("FK_Users_College");

                    b.Navigation("College");
                });

            modelBuilder.Entity("server.Models.College", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("server.Models.Event", b =>
                {
                    b.Navigation("Sports");
                });

            modelBuilder.Entity("server.Models.Sport", b =>
                {
                    b.Navigation("IndividualRegistrations");

                    b.Navigation("Results");

                    b.Navigation("Scores");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("server.Models.Team", b =>
                {
                    b.Navigation("Results");

                    b.Navigation("Scores");

                    b.Navigation("TeamMembers");
                });

            modelBuilder.Entity("server.Models.User", b =>
                {
                    b.Navigation("IndividualRegistrations");

                    b.Navigation("Results");

                    b.Navigation("Scores");

                    b.Navigation("TeamMembers");
                });
#pragma warning restore 612, 618
        }
    }
}
